name: Golang VE CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  cd:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: docker build -t adan-bot .
      - name: Docker tags
        run: |
          docker tag adan-bot ${{ secrets.DOCKER_USER }}/adan-bot:${{ github.sha }}
          docker tag adan-bot ${{ secrets.DOCKER_USER }}/adan-bot:latest
      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/adan-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/adan-bot:latest
      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if : always()
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}
